package com.patchlens.model;

import java.util.List;

/**
 * The structured review brief generated by the AI.
 * Field names match the JSON schema sent to GPT, so Jackson can deserialize
 * the response directly into this record.
 */
public record ReviewResult(
        Summary summary,
        RiskAssessment riskAssessment,
        List<String> suggestedTests,
        List<String> reviewChecklist
) {
    public record Summary(
            String title,
            String overview,
            List<String> mainChanges
    ) {}

    public record RiskAssessment(
            String overallRisk,       // "low" | "medium" | "high"
            List<RiskyFile> riskyFiles
    ) {}

    public record RiskyFile(
            String path,
            String riskLevel,         // "low" | "medium" | "high"
            String reason
    ) {}
}