package com.patchlens.service;

import com.patchlens.model.PatchSuggestion;
import com.patchlens.model.ReviewFinding;
import com.patchlens.model.ValidationStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Formats PatchLens review findings and patches as a Markdown PR comment
 * and posts it via the GitHub Issues API.
 *
 * Posting is skipped when no GitHub token is configured — unauthenticated
 * requests cannot write comments.
 *
 * The comment is intentionally advisory (no approve/reject):
 * the developer decides whether to accept, modify, or ignore each fix.
 */
@Service
public class ReviewCommentService {

    private static final Logger log = LoggerFactory.getLogger(ReviewCommentService.class);

    private static final int MAX_PATCH_PREVIEW_LINES = 40;

    private final GitHubService gitHubService;
    private final String githubToken;

    public ReviewCommentService(GitHubService gitHubService,
                                @Value("${github.token:}") String githubToken) {
        this.gitHubService = gitHubService;
        this.githubToken = githubToken;
    }

    /**
     * Formats findings and patches as Markdown and posts a single review comment.
     *
     * @param owner       GitHub repository owner
     * @param repo        GitHub repository name
     * @param pullNumber  PR number
     * @param findings    detected findings (may be empty — no comment posted if so)
     * @param patches     generated patches; may be fewer than findings (only HIGH/MEDIUM)
     */
    public void postReview(String owner, String repo, int pullNumber,
                           List<ReviewFinding> findings,
                           List<PatchSuggestion> patches) {
        if (findings.isEmpty()) {
            log.info("No findings for {}/{} #{} — skipping review comment", owner, repo, pullNumber);
            return;
        }
        if (githubToken == null || githubToken.isBlank()) {
            log.info("No GitHub token configured — skipping review comment for {}/{} #{}", owner, repo, pullNumber);
            return;
        }

        String body = buildComment(findings, patches);
        gitHubService.postPrComment(owner, repo, pullNumber, body);
    }

    // =====================================================================
    // Formatting
    // =====================================================================

    private String buildComment(List<ReviewFinding> findings, List<PatchSuggestion> patches) {
        Map<UUID, PatchSuggestion> patchByFinding = patches.stream()
                .collect(Collectors.toMap(PatchSuggestion::getFindingId, p -> p,
                        (a, b) -> a));  // keep first if duplicate (shouldn't happen)

        StringBuilder sb = new StringBuilder();

        // Header
        sb.append("### 🔍 PatchLens Review — ")
          .append(findings.size()).append(" finding(s)\n\n");
        sb.append("> Generated by [PatchLens](https://patchlens-alpha.vercel.app). ")
          .append("Findings are advisory — accept, modify, or ignore at your discretion.\n\n");
        sb.append("---\n\n");

        for (ReviewFinding f : findings) {
            appendFinding(sb, f, patchByFinding.get(f.getId()));
        }

        sb.append("---\n");
        sb.append("*PatchLens — AI-assisted code review with sandboxed patch validation*\n");
        return sb.toString();
    }

    private void appendFinding(StringBuilder sb, ReviewFinding finding, PatchSuggestion patch) {
        String severityEmoji = switch (finding.getSeverity()) {
            case HIGH   -> "🔴";
            case MEDIUM -> "🟡";
            case LOW    -> "🟢";
        };

        sb.append("#### ")
          .append(severityEmoji).append(" **[").append(finding.getSeverity()).append("] ")
          .append(finding.getCategory()).append("** — `")
          .append(finding.getFilePath()).append(":")
          .append(finding.getLineStart()).append("–").append(finding.getLineEnd())
          .append("`\n\n");

        sb.append("**").append(finding.getTitle()).append("**\n\n");
        sb.append(finding.getExplanation()).append("\n\n");

        // Patch section (only HIGH/MEDIUM findings get one)
        if (patch != null) {
            String patchText = patch.getPatchText();
            if (patchText != null && !patchText.isBlank()) {
                sb.append("<details>\n<summary>Suggested patch</summary>\n\n");
                sb.append("```diff\n");
                sb.append(truncateLines(patchText, MAX_PATCH_PREVIEW_LINES));
                sb.append("\n```\n\n");

                sb.append("**Validation** — ");
                sb.append(validationLabel(patch.getStatus()));
                if (patch.getRepairAttempts() > 0) {
                    sb.append(" · ").append(patch.getRepairAttempts())
                      .append(" repair attempt(s)");
                }
                sb.append("\n\n");
                sb.append("</details>\n\n");
            }
        }

        sb.append("---\n\n");
    }

    private String validationLabel(ValidationStatus status) {
        return switch (status) {
            case VALIDATED               -> "✅ Policy: PASS";
            case REJECTED_PATCH_APPLY    -> "❌ Patch did not apply";
            case REJECTED_COMPILE        -> "❌ Compile failed";
            case REJECTED_STATIC_ANALYSIS -> "⚠️ Static analysis failed";
            case REJECTED_TEST           -> "❌ Tests failed";
            case REJECTED_POLICY         -> "⚠️ Policy: REJECTED (format/size)";
            case PENDING                 -> "⏳ Pending validation";
        };
    }

    private String truncateLines(String text, int maxLines) {
        String[] lines = text.split("\n");
        if (lines.length <= maxLines) return text;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < maxLines; i++) {
            sb.append(lines[i]).append("\n");
        }
        sb.append("... (").append(lines.length - maxLines).append(" more lines)");
        return sb.toString();
    }
}
